### ISSUE TITLE
Launch on a testnet

### ISSUE THREAD

**Issue by ransonhobbes** [ransonhobbes/stardust#6]
- [x] Add support for interacting with already-deployed Azimuth/Ecliptic
- [x] Launch Azimuth/Ecliptic on an Eth testnet (or find an already-deployed version)
- [ ] Launch Stardust on the same testnet and try interacting with them

**Comment by ransonhobbes** [comment]
Deploy script added in #43, successfully deployed on ropsten (and linked to existing azimuth deployment there): https://ropsten.etherscan.io/tx/0x3fa11edcdfee4fe64d52ce82f4b555e3b9dc4d95e9bfdc025b2afe88bc70b0b3
